// Developer Express Code Central Example:
// How to change background color for modified cells
// 
// This example shows how to highlight grid cells that have been edited by a user.
// When a user changes a value and leaves the modified cell, the cell turns
// red.
// Update:
// This approach may look cumbersome if you have a lot of columns.
// We've prepared another example demonstrating how to accomplish a similar task
// with a dictionary of cell states: http://www.devexpress.com/scid=E4025.
// See
// Also:
// http://www.devexpress.com/scid=E841
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E1297

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighlightModifiedCells.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
